### ISSUE TITLE
 python3-dev

### ISSUE THREAD

**Issue by abtionlove** [Ultimaker/libArcus#107]
How to install python3 Dev and python3 SIP dev through cygwin64 under windows？

**Comment by nallath** [comment]
Have you tried installing it via pip?

**Comment by abtionlove** [comment]
> Have you tried installing it via pip?

PIP installation requires python3 Dev and python3 SIP dev installation packages, which I can't find.

**Comment by Ghostkeeper** [comment]
I think this is your solution: https://stackoverflow.com/questions/21843714/cygwin-gcc-issue-cannot-find-python-h?answertab=votes#tab-top

**Comment by abtionlove** [comment]
> I think this is your solution: https://stackoverflow.com/questions/21843714/cygwin-gcc-issue-cannot-find-python-h?answertab=votes#tab-top

OK,Thank you
