### ISSUE TITLE
Building in Windows

### ISSUE THREAD

**Issue by sarahSamonte** [Ultimaker/libArcus#12]
When I try to configure in cmake, I got this error: 
![error](https://cloud.githubusercontent.com/assets/11551855/10875437/658d6946-816d-11e5-9633-05a4f321f932.png)

When I tried setting PROTOBUF_INCLUDE_DIR to its location
set(PROTOBUF_INCLUDE_DIR "C:/MinGW/msys/1.0/local/protobuf-master")
the error still exists.

I am using "MSYS Makefiles" for generating the files.

**Comment by Ghostkeeper** [comment]
Did you also point `PROTOBUF_LIBRARY` to ProtoBuf's binary library?

**Comment by awhiemstra** [comment]
You should be able to select both the include dir and library path from CMake's GUI. Once done, things should compile.

**Comment by sarahSamonte** [comment]
I was able to configure it. But when I clicked Generate, I had two warnings:
![isuue2](https://cloud.githubusercontent.com/assets/11551855/10911956/38eed2ce-8282-11e5-89f7-b6d24d0057e8.png)

And when I tried calling make in the command prompt, I had an error regarding protobuf.

I set both vars: PROTOBUF_LIBRARY and PROTOBUF_INCLUDE_DIR to the path of protobuf_master (as shown in the warning). Did I set those variables wrong?

**Comment by awhiemstra** [comment]
Yes, the PROTOBUF_LIBRARY variable needs to point to the library file, not a directory. Somewhere in C:\MinGW\msys\1.0\local\protobuf-master should be a libprotobuf.dll or .a that you should point to.

**Comment by airycanon** [comment]
@sarahSamonte  You could try "pacman -S protobuf-devel",this worked in my MSYS2.

**Comment by yingzhang1109** [comment]
@airycanon Hi, I met the same problem. I am wondering that, what did you mean for try "pacman -S protobuf-devel" ?

**Comment by airycanon** [comment]
@yingzhang1109 It is a mistake,pacman is only for MSYS2.

**Comment by Ghostkeeper** [comment]
Pacman is a package manager for the MSYS environment.

To fix this, @yingzhang1109, you should find the development version of Protobuf for your platform. Or download and compile Protobuf yourself.
