### ISSUE TITLE
sip.h no such file or directory

### ISSUE THREAD

**Issue by Robertbaelde** [Ultimaker/libArcus#17]
I'm trying to install libArcus. But the make command fails with the error that it could not find sip.h. while sip is installed. 

```
 cmake ..
-- Found SIP version: 4.15.5
-- Configuring done
-- Generating done
-- Build files have been written to: /root/cura/libArcus/build

make
[ 26%] Built target Arcus
[ 31%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart0.cpp.o
In file included from /root/cura/libArcus/build/python/sipArcuspart0.cpp:10:0:
/root/cura/libArcus/build/python/sipAPIArcus.h:11:17: fatal error: sip.h: No such file or directory
 #include <sip.h>
                 ^
compilation terminated.
make[2]: *** [CMakeFiles/python_module_Arcus.dir/python/sipArcuspart0.cpp.o] Error 1
make[1]: *** [CMakeFiles/python_module_Arcus.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by fieldOfView** [comment]
I think you have to install sip-dev as well as sip. Possibly also python3-sip

**Comment by Robertbaelde** [comment]
Installed those packages, but unfortunately didn't fix the problem

**Comment by fieldOfView** [comment]
How about python3-sip-dev? I recently set up a VM with a dev installation of Cura (with libArcus), and am retracing my .bash_history.

**Comment by Robertbaelde** [comment]
Tnx, that solved the issue!

**Comment by jackha** [comment]
@fieldOfView You just made my day ^^

**Comment by fieldOfView** [comment]
Your day is easily made

**Comment by kalkun** [comment]
sip can be gotten from [riverbankcomputing.com](https://www.riverbankcomputing.com/software/sip/download). The `configure.py` should be run with `python3` then
```
make
make install
```
afterwards libArcus should find `sip`. You can test in python3 by using `import sip`.
