### ISSUE TITLE
AttributeError: module 'Arcus' has no attribute 'SocketListener'

### ISSUE THREAD

**Issue by fabianrodrigo** [Ultimaker/libArcus#19]
Hi, people. I'm new with Cura. I'm trying to install it. I have installed Protobuf, libArcus and Uranium in my MacBookPro with OSX Yosemite.

One of the cura plugins named CuraEngineBackend is failing. I isolate the issue executing this python call in bash:

python3.5 -c "import plugins.CuraEngineBackend"

And this is the exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/[project_dir]/Cura/plugins/CuraEngineBackend/__init__.py", line 5, in <module>
    from . import CuraEngineBackend
  File "[project_dir]/Cura/plugins/CuraEngineBackend/CuraEngineBackend.py", line 4, in <module>
    from UM.Backend.Backend import Backend
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/UM/Backend/Backend.py", line 4, in <module>
    from UM.Backend.SignalSocket import SignalSocket
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/UM/Backend/SignalSocket.py", line 32, in <module>
    class _SocketListener(Arcus.SocketListener):
AttributeError: module 'Arcus' has no attribute 'SocketListener'

I'm seing the libArcus install log and I don't see error messages:

(Cura) Fabians-MacBook-Pro:[project_dir] fabian$ cd libArcus/
(Cura) Fabians-MacBook-Pro:libArcus fabian$ mkdir build
mkdir: build: File exists
(Cura) Fabians-MacBook-Pro:libArcus fabian$ mkdir build
(Cura) Fabians-MacBook-Pro:libArcus fabian$ cd build
(Cura) Fabians-MacBook-Pro:build fabian$ cmake ..
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/local/lib/libprotobuf.dylib  
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.5.1", minimum required is "3.4.0") 
-- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib (found suitable version "3.5.1", minimum required is "3.4.0") 
-- Found SIP version: 4.17
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   Arcus

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: [project_dir]/libArcus/build
(Cura) Fabians-MacBook-Pro:build fabian$ make
Scanning dependencies of target Arcus
[  4%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.o
[  9%] Building CXX object CMakeFiles/Arcus.dir/src/SocketListener.cpp.o
[ 13%] Building CXX object CMakeFiles/Arcus.dir/src/MessageTypeStore.cpp.o
[ 18%] Building CXX object CMakeFiles/Arcus.dir/src/PlatformSocket.cpp.o
[ 22%] Building CXX object CMakeFiles/Arcus.dir/src/Error.cpp.o
[ 27%] Linking CXX shared library libArcus.dylib
[ 27%] Built target Arcus
[ 31%] Generating python/sipArcuspart0.cpp, python/sipArcuspart1.cpp, python/sipArcuspart2.cpp, python/sipArcuspart3.cpp, python/sipArcuspart4.cpp, python/sipArcuspart5.cpp, python/sipArcuspart6.cpp, python/sipArcuspart7.cpp

Scanning dependencies of target python_module_Arcus
[ 36%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart0.cpp.o
[ 40%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart1.cpp.o
[ 45%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart2.cpp.o
[ 50%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart3.cpp.o
[ 54%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart4.cpp.o
[ 59%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart5.cpp.o
[ 63%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart6.cpp.o
[ 68%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart7.cpp.o
[ 72%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o
[ 77%] Linking CXX shared module Arcus.so
[ 77%] Built target python_module_Arcus
[ 81%] Running C++ protocol buffer compiler on example.proto
[ 86%] Running Python protocol buffer compiler on example.proto
Scanning dependencies of target example
[ 90%] Building CXX object examples/CMakeFiles/example.dir/example.cpp.o
[ 95%] Building CXX object examples/CMakeFiles/example.dir/example.pb.cc.o
[100%] Linking CXX executable example
[100%] Built target example
(Cura) Fabians-MacBook-Pro:build fabian$ make install
[ 27%] Built target Arcus
[ 77%] Built target python_module_Arcus
[100%] Built target example
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/python3.4/site-packages/Arcus.so
-- Installing: /usr/local/lib/libArcus.1.0.0.dylib
-- Up-to-date: /usr/local/lib/libArcus.2.dylib
-- Up-to-date: /usr/local/lib/libArcus.dylib
-- Up-to-date: /usr/local/include/Arcus/Socket.h
-- Up-to-date: /usr/local/include/Arcus/SocketListener.h
-- Up-to-date: /usr/local/include/Arcus/Types.h
-- Up-to-date: /usr/local/include/Arcus/ArcusExport.h
-- Up-to-date: /usr/local/include/Arcus/MessageTypeStore.h
-- Up-to-date: /usr/local/include/Arcus/Error.h
-- Installing: /usr/local/lib/cmake/Arcus/Arcus-targets.cmake
-- Installing: /usr/local/lib/cmake/Arcus/Arcus-targets-noconfig.cmake
-- Installing: /usr/local/lib/cmake/Arcus/ArcusConfig.cmake
-- Installing: /usr/local/lib/cmake/Arcus/ArcusConfigVersion.cmake

But the SocketListener class is not included on Arcus/__init__.py.

Can you tell me if it is a bug? Or I make a mistake on the install process.

Thanks a lot for your time

**Comment by nallath** [comment]
Seems that the paths are not correctly set. The same code works correctly with me. Could you try adding /usr/local/lib/python3/dist-packages/ to your PYTHONPATH

**Comment by fabianrodrigo** [comment]
Thank you for your response

I tried setting the PYTHONPATH to:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/

and also to:

/usr/local/lib/python3.5/site-packages/

also setting the cmake variables:

cmake .. -DPYTHON_SITE_PACKAGES_DIR=/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/

and 

cmake .. -DPYTHON_SITE_PACKAGES_DIR=/usr/local/lib/python3.5/site-packages/

The result is the same.

How can I verify manually that the C++ class SocketListener is correctly connected to Python3.5?

python3.5 -c "import Arcus" 

is working but:

python3.5 -c "import Arcus;sl=Arcus.SocketListener()"

doesn't work

I suppose that if SocketListener is installed, it needs to be included in the __int__.py file in the Arcus folder. Does it make sense? It's a weird exception hehehe.

**Comment by daid** [comment]
I ran into this same problem today. (On windows, assume it's the same issue)

First off, you need to clean out your system of any left over libArcus files from older installs. The __init__.py file is no longer present in the latest installations, but does not get removed.

so:
```
python3.5
import Arcus
print(Arcus.__file__)
```
Should print:
`somethingsomething/python3.5/lib/site-packages/Arcus.pyd` and not:
`somethingsomething/python3.5/lib/site-packages/Arcus/__init__.py`

If it does contain the last bit. Remove that Arcus folder. Delete your whole libArcus build directory (do a fresh checkout) and build it from there.

**Comment by fabianrodrigo** [comment]
Thank you, your response was so useful. Cura is working now.

I want to ask you a final question. Cura is calling plugins and resources of Uranium github project. What is your method for sharing those files with Cura?

I'm very intersting in continue working with Cura and perhaps in the future, working with you. It will be amazing =D

**Comment by Ghostkeeper** [comment]
For development, we install the Uranium packages elsewhere and refer our PYTHONPATHs to include the Uranium repository.

The installer / packager does something similar, but just puts the contents of the two repositories alongside each other.

**Comment by awhiemstra** [comment]
And if you are looking for the code to do that, check the PluginRegistry and Resources classes in Uranium. They do the lookup of files in combination with application-set paths.

**Comment by fabianrodrigo** [comment]
Great, thank you people =D
