### ISSUE TITLE
Windows install: no make file

### ISSUE THREAD

**Issue by PatternSpacePrime** [Ultimaker/libArcus#2]
![libarcus_cmake](https://cloud.githubusercontent.com/assets/11967402/7886788/5a068a56-05fa-11e5-9b6f-13fd0fa426e6.jpg)
![libarcvus_visualstudi](https://cloud.githubusercontent.com/assets/11967402/7886789/5a06ef0a-05fa-11e5-81c2-c7e8f9542f5a.jpg)

When attempting to install libArcus on Windows 8.1 (using MinGW / MSys) after running CMAKE, there are no make files generated so the MAKE command fails (Step 3 in the the BUILDING section of the readme).  It looks like Visual Studio solutions and projects are created. 

When attempting to build the Arcus.sln file via Visual Studio, it keeps throwing Unresolved Externals errors in relation to protobuf even though I followed the Protobuf install directions with no errors.

**Comment by Ghostkeeper** [comment]
It looks like CMake was using its generator for Visual Studio (and then you had a problem linking it with a cross-compiled Protobuf). Did you instruct CMake to generate MinGW makefiles?

Building on Windows, I prefer to use the CMake GUI and it always asks me which makefiles I'd like to generate when I first "Configure" it on a new folder. You can select MinGW Makefiles from a drop-down menu. If it doesn't ask, you can do File->Delete Cache and click Configure again, and it should ask again. If you're using CMake via the command line, adding the option

    -G "MinGW Makefiles"

should instruct CMake to produce Makefiles that work with MinGW. After that there will be some variables to specify (specifically where to find Protobuf) and you might want to add the compiler option -m64 to the CXX and C compiler flags if you're building 64-bit (but of course, all other parts of the program should be 64-bit then too). Then, when you Generate, a normal Makefile should appear in your build directory.

For libArcus, it's not necessary to build it within msys. Just plain mingw32-make should work fine. We also have a version of [Protobuf](https://github.com/Ultimaker/protobuf) with CMake files that shouldn't require the msys environment like Protobuf normally does :)

**Comment by BagelOrb** [comment]
@PatternSpacePrime Can you get it built now?

**Comment by daid** [comment]
Note, I'm building fine with CMake and windows. So this is more of a user error/documentation problem then a problem in the code.

**Comment by PatternSpacePrime** [comment]
Using the MinGW cmake flag output a makefile as you predicted. However using MAKE on the generated files was unsuccessful (and yes I input the proper paths to my protobuf libs and even tried the m64 flags). I think I'm just going to wait until the whole CuraEngine and new Cura project get cleaned up a little with better documentation before diving in. I'm just going to use Cura SteamEngine for our purposes in the mean time. Thanks guys,

**Comment by awhiemstra** [comment]
It is not so much an issue with our build files but rather with CMake. CMake knows at least 3 different generators for Windows: A Visual Studio project generator, a MinGW32-make generator and an MSYS generator. In your case, since you are running from inside MSYS, you need to use the MSYS generator, since the paths to tools are different between MinGW32-make and MSYS. Alternatively, you could run mingw32-make on the makefiles from a normal command prompt.

**Comment by teddyorkie** [comment]
I can generate makefiles using either MSYS or MinGW generator from CMake. But in both cases, I can't build with either make or mingw32-make. It keeps saying 'mutex' in namespace 'std' does not name a type. I've stucked here for a while just like PatternSpacePrime. I'm using Window 7 64bit machine. Anyone has any idea?

**Comment by daid** [comment]
Your compiler is dated. Use minimal the i686-4.9.2-posix-dwarf-rt_v3-rev1 compiler from the mingw-w64 project.

**Comment by teddyorkie** [comment]
Thanks. I had to recompile libtool, autoconf and protobuf under this compiler for it to work. For anyone having the same problem, here's the cmake command I used:
'''
cmake .. -G "MSYS Makefiles" -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++ -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_INSTALL_PREFIX=/local
'''
So much trouble for this little library. Now e CuraEngine itself is giving me crap about isinf not declared in this scope.

**Comment by Ghostkeeper** [comment]
That one's on us. `isinf` is placed in the std namespace so it should be called from there. I'll fix that right up.

**Comment by pratikshashroff** [comment]
how can I resolve the same error (raised by PatternSpacePrime) in case of ubuntu?
How to generate a makefile during the build of libarcus on Ubuntu?

**Comment by Ghostkeeper** [comment]
I can't find anything called PatternSpacePrime in libArcus or CuraEngine. In any case, you'd have to find out in what namespace the PatternSpacePrime is and prepend `<namespace>::` at every place where it is used from a different namespace.

The makefile is generated with CMake. Make a build directory in the libArcus folder, navigate to it in your terminal and call `cmake ..` from the build directory. That should generate a makefile. You may have to use cmake-gui if not all dependencies are detected correctly.

**Comment by pratikshashroff** [comment]
thank you very much for your response.Sorry for the confusing first question above related to 'PatternSpacePrime'
Anyway, I downloaded the cmake-gui and made some progress with the 'cmake' and 'make' steps.
Now, I am getting error in the 'make install' step as -
CMake Error at cmake_install.cmake:48 (FILE):
  file INSTALL cannot copy file

any suggestions on this one, would be really helpful.
