### ISSUE TITLE
FindSIP.py is run with Python 2 instead of 3

### ISSUE THREAD

**Issue by onitake** [Ultimaker/libArcus#23]
While FindSIP.cmake requires Python 3.4.0, FindSIP.py is apparently run with the Python 2 interpreter on Debian.

Since my system only has python3-sip installed, this results in the following error:
```
Traceback (most recent call last):
  File "~/cura/libArcus/cmake/FindSIP.py", line 10, in <module>
    sipcfg = sipconfig.Configuration()
AttributeError: 'module' object has no attribute 'Configuration'
CMake Error at cmake/FindSIP.cmake:58 (MESSAGE):
  Could not find SIP
Call Stack (most recent call first):
  CMakeLists.txt:22 (find_package)
```

Running FindSIP.py with python3 works and produces the expected output.

**Comment by onitake** [comment]
Please disregard this, it was in fact finding and executing a Python 3 interpreter - but the wrong one.
My system has Python 3.4 and Python 3.5 installed, but the PyQt packages and SIP are only available to Python 3.5. Removing Python 3.4 fixed the issue.

**Comment by Ghostkeeper** [comment]
Hmm, interesting, since basically all of our development team uses Python 3.4. I'm interested to see whether you manage to get everything up and running in 3.5.

I've tried with my computer at home on 3.5 but ran into different issues with the py2exe packaging.

**Comment by thopiekar** [comment]
I'm using Python 3.5 in Ubuntu xenial, which is beta at the moment, and it is working very well so far.

**Comment by onitake** [comment]
I think I found why it didn't work:
```
$ dpkg -L python3-sip
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/sipconfig.py
/usr/lib/python3/dist-packages/sip.cpython-35m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/sipconfig_nd5.py
/usr/share
/usr/share/doc
/usr/share/doc/python3-sip
/usr/share/doc/python3-sip/changelog.Debian.gz
/usr/share/doc/python3-sip/changelog.gz
/usr/share/doc/python3-sip/copyright
/usr/share/python3
/usr/share/python3/dist
/usr/share/python3/dist/python3-sip
```

sip.cpython-35m-x86_64-linux-gnu.so is specifically compiled for the most recent Python (3.5m) and not available to the 3.4 interpreter, as far as I can tell.

This is Debian testing, though, so the semi-breakage is not that surprising.

**Comment by thopiekar** [comment]
Packages built for testing are only using testing packages to solve the dependencies. So if there is only Python 3.5 in testing you'll just find 3.5 modules in the packages.
Btw. if you really need 3.4 modules you can rebuild SIP via
```
apt-get source sip-dev
cd sip
dpkg-buildpackge -j4
```

**Comment by onitake** [comment]
Aside from that, Cura is working fine with Python 3.5 so far, but I'm still getting some errors and a segfault on exit. Here's some output: https://gist.github.com/onitake/a06362c72d8eece11829

@thopiekar If it works fine with Python 3.5, I don't really need to have 3.4 installed. But thanks for the suggestion. 3.4 is still in stretch, because some packages depend on it. As soon as those are updated to work with 3.5, 3.4 will likely go away.
