### ISSUE TITLE
cmake cannot find PROTOBUF

### ISSUE THREAD

**Issue by easonyuexcellent** [Ultimaker/libArcus#26]
I test %PROTOBUF_LIBRARY%, % PROTOBUF_INCLUDE_DIR%, shows my path.

`CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Protobuf (missing: PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR)
  (Required is at least version "3.0.0")
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/FindProtobuf.cmake:308 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/apps/libArcus-master/build/release/CMakeFiles/CMakeOutput.log".`

**Comment by elviswoo** [comment]
I have been suffered the same problem with you,   have you solved this problem?

**Comment by ketjow4** [comment]
Try to use CMakeGUI and after clicking configure which will fail at first you can set path to your Protobuf location (inlcude and library location). It might be necessary to tick "Advanced options" to see those paths.

**Comment by eldem** [comment]
set the following env variables: 
CMAKE_INCLUDE_PATH = [YOUR_PATH]\protobuf\src\google\protobuf # which points at the bottom of your include path.
CMAKE_LIBRARY_PATH = [YOUR_PATH]\protobuf\src\.libs #which should contain "libprotobuf" "libprotobuf-lite" "liteprotoc" .lib files.

You might also need to add protobuf ([YOUR_PATH]\protobuf\src) to your $PATH system variable if you are on Windows.

Now run cmake: 
cmake .. -G "MSYS Makefiles" # Replace 'MSYS' if you are using a different generator.

**Comment by adaxidedakaonang** [comment]
@eldem Hi,I use mac and I meet the same question while building caffe, can you please tell where should I to set these two bariables? This is my error:

CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindProtobuf.cmake:543 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/ProtoBuf.cmake:4 (find_package)
  cmake/Dependencies.cmake:43 (include)
  CMakeLists.txt:46 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/Arduino/caffe/CMakeFiles/CMakeOutput.log".

Thanks.

**Comment by Ghostkeeper** [comment]
Do you have Protobuf installed? If so, could you set `Protobuf_LIBRARY_DEBUG`, `Protobuf_LIBRARY_RELEASE`, `Protobuf_PROTOC_EXECUTABLE` and `Protobuf_INCLUDE_DIR` to respectively the debug library, release library, protoc and header directory of Protobuf?
