### ISSUE TITLE
nmake Building error

### ISSUE THREAD

**Issue by easonyuexcellent** [Ultimaker/libArcus#27]
[  4%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.obj
Socket.cpp
c:\apps\libarcus\src\Types.h(38) : error C2039: 'shared_ptr' : is not a member of 'std'
c:\apps\libarcus\src\Types.h(38) : error C2143: syntax error : missing ';' before '<'
c:\apps\libarcus\src\Types.h(38) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\apps\libarcus\src\Socket.h(128) : error C2061: syntax error : identifier 'MessagePtr'
c:\apps\libarcus\src\Socket.h(133) : error C2146: syntax error : missing ';' before identifier 'takeNextMessage'
c:\apps\libarcus\src\Socket.h(133) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\apps\libarcus\src\Socket.h(133) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\apps\libarcus\src\Socket.h(133) : warning C4183: 'takeNextMessage': missing return type; assumed to be a member function returning 'int'
c:\apps\libarcus\src\Socket.h(140) : error C2146: syntax error : missing ';' before identifier 'createMessage'
c:\apps\libarcus\src\Socket.h(140) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\apps\libarcus\src\Socket.h(140) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\apps\libarcus\src\Socket.h(140) : warning C4183: 'createMessage': missing return type; assumed to be a member function returning 'int'
c:\apps\libarcus\src\Socket.h(148) : error C2039: 'unique_ptr' : is not a member of 'std'
c:\apps\libarcus\src\Socket.h(148) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\apps\libarcus\src\Socket.h(148) : error C2143: syntax error : missing ';' before '<'
c:\apps\libarcus\src\Socket.h(148) : error C2238: unexpected token(s) preceding ';'
c:\apps\libarcus\src\Socket_p.h(19) : fatal error C1083: Cannot open include file: 'thread': No such file or directory

**Comment by daid** [comment]
c:\apps\libarcus\src\Types.h(38) : error C2039: 'shared_ptr' : is not a member of 'std'

Your compiler is too old. You most likely need a compiler from: http://mingw-w64.org/
I'm using the i686-4.9.2-posix-dwarf-rt_v3-rev1 version.

**Comment by Ghostkeeper** [comment]
Needs to support C++11.

**Comment by easonyuexcellent** [comment]
Thank U, now I understand
