### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sajjadul-wematter** [Ultimaker/libArcus#28]
Hello,

protobuf is already installed in ubuntu system from repository. Then while compiling this library from source, the system gives the following error:

///////////////////////////////////////////////////////////////
[ 31%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o
/home/sajjad/Downloads/Arcus/libArcus-master/python/PythonMessage.cpp:24:40: fatal error: google/protobuf/reflection.h: No such file or directory
compilation terminated.
CMakeFiles/python_module_Arcus.dir/build.make:270: recipe for target 'CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o' failed
make[2]: *** [CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/python_module_Arcus.dir/all' failed
make[1]: *** [CMakeFiles/python_module_Arcus.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
//////////////////////////////////////////////////////////////

Any hint to get around this issue ?

Thanks

**Comment by Ghostkeeper** [comment]
Looks like you're using a different version of Protobuf. Protobuf has [had that file for a while](https://github.com/google/protobuf/blob/master/src/google/protobuf/reflection.h). Or maybe you also need to download development headers for Protobuf (`libprotobuf-dev`).

**Comment by sajjadul-wematter** [comment]
It was already installed when I encountered this issue.

**Comment by Ghostkeeper** [comment]
Does CMake find the include directory for Protobuf?

**Comment by thopiekar** [comment]
@Ghostkeeper, I guess @sajjadul-wematter installed protobuf 2 via APT.
@sajjadul-wematter, please add my PPA where you can find protobuf 3 and update the libprotobuf-dev package. Cura is also available there. So you don't even have to build everything on your own.
https://launchpad.net/~thopiekar/+archive/ubuntu/cura

**Comment by sajjadul-wematter** [comment]
cmake .. ubder build directory returns the following :


////////////////////////////////////////////////////
sajjad@sajjad-G74Sx:~/Downloads/Arcus/libArcus-master/build$ cmake ..-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib/i386-linux-gnu/libprotobuf.so  
-- Found PythonInterp: /usr/bin/python3.4 (found suitable version "3.4.3", minimum required is "3.4.0") 
-- Found PythonLibs: /usr/lib/i386-linux-gnu/libpython3.4m.so (found suitable version "3.4.3+", minimum required is "3.4.0") 
-- Found SIP version: 4.16.9
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sajjad/Downloads/Arcus/libArcus-master/build
////////////////////////////////////////////////////

It does not mention anything about the include directory. Anyway, looked for it through the ccmake and mention the include directory and now I have new installation problem.

I have several other API installations dependent on the current installation of protobuf through APT. I wonder how the update from the new repository mentioned by @thopiekar effect them.

**Comment by sajjadul-wematter** [comment]
The issue is solved. Thanks @thopiekar .

**Comment by thopiekar** [comment]
No problem. Happy hacking 😉
