### ISSUE TITLE
LibArcus - Ubuntu 14.04

### ISSUE THREAD

**Issue by rberros** [Ultimaker/libArcus#31]
Hi Guys,

I want to build the library. I installed libtool (sudo apt-get install libtool) and I followed the steps to install protobuf.
But when I try to build the library i have this problem.
![image](https://cloud.githubusercontent.com/assets/19324035/15210473/f2af584c-1836-11e6-84d7-ee45a8e41b01.png)

However, I already did these steps:
_Navigate to protobuf-master/python
sudo apt-get install python3-setuptools
sudo python3 setup.py build
sudo python3 setup.py install_

Can anybody help me, please?

Thanks in advance

**Comment by thopiekar** [comment]
```python3-all-dev``` seems to be missing.
As the error message says, CMake is not able to find it anywhere.

By the way, why do you still use Ubuntu 14.04? If you upgrade to a more recent version you can use precompiled packages.
For the moment if you like to use the .deb bundle supported by Ultimaker, please note that there are problems with Ubuntu Xenial at the moment.

Regards 😉

**Comment by fieldOfView** [comment]
14.04 was the most up-to-date LTS, until not so long ago, which is why I guess many people are still using it (I was, but have now upgraded to 16.04 LTS)

**Comment by thopiekar** [comment]
Ah, yes, that's correct. I just upgrade on every regular release.
I'm not 100%ly sure about the reason, but I had problems creating packages
for 14.04 in my PPA, but I didn't cared more about that, because I don't
use that version 🙄

**Comment by jellespijker** [comment]
Closing this since we no longer support 14.04 and have moved on to 20.04
