### ISSUE TITLE
tag a 1.1.0 release please

### ISSUE THREAD

**Issue by greyltc** [Ultimaker/libArcus#32]
Please tag a 2.1.0 release to go along with all the other 2.1.0 releases for the other bits of the software stack: uranium, cura etc.

**Comment by BagelOrb** [comment]
It's on the 2.1 branch..
Op 24 mei 2016 13:42 schreef "Grey Christoforo" <notifications@github.com>:

**Comment by greyltc** [comment]
Hi @BagelOrb, I see there is a branch in this repo named 2.1 where I assume 2.1 related development is taking place.

I made this issue to request a dev here to make a git tag that points to a specific commit as being a stable 2.1.0 release (as all the downstream projects that depend on libArcus have done).

**Comment by awhiemstra** [comment]
The thing is that I want to decouple libArcus releases from Cura releases and make Cura use a proper release of libArcus instead of a git checkout. So what you are actually asking is to make a proper 1.1 release of libArcus that packages can depend on. :)

I will try and see if I can do this tomorrow and update everything to use the proper release. I am quite swamped with work though, so it might be a few more days before it happens.

**Comment by BagelOrb** [comment]
Still it would be nice to know up to which commit exactly is in the 2.1.0
release.
As we haven't done a separate 1.1 release for libArcus, we should tag it as
2.1 for now.
Op 25 mei 2016 11:37 schreef "awhiemstra" <notifications@github.com>:

**Comment by thopiekar** [comment]
2.1.3 has been tagged, see: https://github.com/Ultimaker/libArcus/releases
But the true libArcus version is 1.1.0 (or will be): https://github.com/Ultimaker/libArcus/commit/9c500ce8a3edf8f663e6935ef5145274524c8a4c

**Comment by Ghostkeeper** [comment]
Good that you mention it, because I see that that 2.1.3 tag is wrong. It should've been made on the 2.1 branch and not include any other commits that were later added to master.

**Comment by thopiekar** [comment]
Btw. shouldn't make more sense if we use the correct version?
https://github.com/Ultimaker/libArcus/commit/9c500ce8a3edf8f663e6935ef5145274524c8a4c

We could tag this "2.1.3" release as "cura-2.1.3", in meaning of: "This is the release, which has been used to build 2.1.3"?
Would be less confusing than it already is..

**Comment by fieldOfView** [comment]
No, because there are other applications that use libArcus as well. In that regard, libArcus is like eg protobuf. We don;t tag protobuf with 2.1.3.
