### ISSUE TITLE
Missing check for Initial state

### ISSUE THREAD

**Issue by Ocarthon** [Ultimaker/libArcus#37]
In [Socket::connect](https://github.com/Ultimaker/libArcus/blob/master/src/Socket.cpp#L122) there is a check if the socket is in the initial state. But in [Socket::listen](https://github.com/Ultimaker/libArcus/blob/master/src/Socket.cpp#L153) that check is missing. Shouldn't that there be in place too?

**Comment by sedwards2009** [comment]
Yes, I agree. It should do a better job of preventing listen() being called at the wrong time.
