### ISSUE TITLE
Try and use libprotobuf-lite

### ISSUE THREAD

**Issue by oliv3r** [Ultimaker/libArcus#4]
For embedded systems, the use of libprotobuf-lite could safe precious resources. Unless we have a hard dependancy on the full libprotobuf, we could suffice with libprotobuf-lite.

**Comment by Renha** [comment]
Agreed. I am compiling protobuf on my Jolla for 6 hours right now.

**Comment by awhiemstra** [comment]
I actually did some basic tests with this a while ago. The end conclusion is that currently this is impossible since we make use of the introspection capabilities of Protobuf, which are not available with protobuf-lite.
