### ISSUE TITLE
LibArcus -Unable to import sipconfig

### ISSUE THREAD

**Issue by yousiri** [Ultimaker/libArcus#42]
Hi Guys
today, I have installed Protobuf and  cmake LibArcus, then I want to make it, but error occur, just as the following:
![image](https://cloud.githubusercontent.com/assets/20435188/18696979/e340f84a-7fef-11e6-9958-645a93781378.png)

Can anybody help me, please?

Thanks in advance

**Comment by Ghostkeeper** [comment]
You need SIP to compile libArcus for Python. Try this command:

    python3 -m pip install SIP

**Comment by yousiri** [comment]
thank you for your answer and I try it just now, but it also causes a error：
 
![image](https://cloud.githubusercontent.com/assets/20435188/18710386/9a065baa-8037-11e6-8eb8-7065257421ba.png)
no SIP suits for it??

**Comment by thopiekar** [comment]
Isn't it called "Sip" instead? 🤔

**Comment by cinderblock** [comment]
I fixed this by installing python bindings for protobuf. On my system:

```
sudo apt-get install -y python-protobuf
```

**Comment by thopiekar** [comment]
@cinderblock `python(2)-*` doesn't make any sense here, as Cura only supports Python >= 3.
I only can image that there was a set of recommendations around the packages, which installed sip-dev at the end.
.

**Comment by cinderblock** [comment]
I'm not very familiar with the python world but I'm rather certain that was the only command I ran between the build failing and working. I'm not sure what else could have been installed. Unfortunately I closed that terminal window and cannot see the list of deps that were also installed.

For what it's worth, I was able to build libArcus (5711984ce978d8c88381fd29f7e714b068cba816) even though sid-dev is not installed:
```
pi@raspberryprint:~ $ sudo apt-get install sip-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  python-sip python-sip-dev
Suggested packages:
  python-sip-doc
The following NEW packages will be installed:
  python-sip python-sip-dev sip-dev
0 upgraded, 3 newly installed, 0 to remove and 25 not upgraded.
Need to get 240 kB of archives.
After this operation, 647 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
pi@raspberryprint:~/libArcus/build $ make
[ 26%] Built target Arcus
[ 78%] Built target python_module_Arcus
[100%] Built target example
```
