### ISSUE TITLE
release snapshots please

### ISSUE THREAD

**Issue by l3iggs** [Ultimaker/libArcus#5]
Please give us release snapshots for this project that correlate to releases for uranium and cura.

**Comment by awhiemstra** [comment]
I have pushed a tag for 15.06.03 and will remember to also tag for future releases.

**Comment by l3iggs** [comment]
Great thank you!

It would be really cool if you could tag/release cura-build as well!

**Comment by l3iggs** [comment]
By the way, I'm asking for all this because I'm in the process of packaging cura for Arch Linux

**Comment by awhiemstra** [comment]
Pushed a tag to cura-build as well.
