### ISSUE TITLE
LibArcus build is broken on Linux with Python 3.x

### ISSUE THREAD

**Issue by pathes** [Ultimaker/libArcus#51]
https://github.com/Ultimaker/libArcus/commit/08a710858cd94b59160fc063cad94b7369f2a096 introduced a change in FindSIP.py that doesn't allow to "import sip" when sys.platform isn't "win32".

**Comment by thopiekar** [comment]
@pathes I'm noticing no problems building libArcus, neither on master nor on the latest stable branch. For me it looks like something else is going wrong.

**Comment by awhiemstra** [comment]
When sipconfig does not exist FindSip falls back to a different method that was written to handle how sip on Windows is (was?) installed. However, it should be fairly simple to make it more generic so other systems are also handled properly.

**Comment by sedwards2009** [comment]
There is an expectation from Riverbank computing that if you are using the sip code generator in your build then you can and should build your own sip yourself. Riverbank computing no longer distributes a sip.exe like they did in the past.

**Comment by ynotstartups** [comment]
error when you do python3  FindSIP.py
