### ISSUE TITLE
issues when developing protobuf on win10

### ISSUE THREAD

**Issue by yingzhang1109** [Ultimaker/libArcus#53]
hi, I am very new to this.
when I am trying to install protobuf, I run autogen.sh, and I got this

$ ./autogen.sh
++ autoreconf -f -i -Wall,no-obsolete
Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4                 te::ChannelDefs module) (@INC contains: /mingw/share/autoconf /usr/lib/perl5/sit                 e_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/ve                 ndor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /c/MinGW/bin                 /autoreconf-2.68 line 40.
BEGIN failed--compilation aborted at /c/MinGW/bin/autoreconf-2.68 line 40.

can anyone help me with that? thanks in advance

**Comment by awhiemstra** [comment]
Don't use the autoconf buildsystem. Use the CMake buildsystem, it is properly cross-platform. It can be found in the cmake/ subdir of the protobuf source dir. To use it, make a build directory then run "cmake $protobuf_source_dir/cmake". Or you can use cmake-gui.

**Comment by Ghostkeeper** [comment]
Protobuf does support autoconf as a build system as far as I know, but if you have problems with that you should ask the Protobuf developers, not us.
