### ISSUE TITLE
Building on  Windows

### ISSUE THREAD

**Issue by masklu** [Ultimaker/libArcus#54]
When I try to configure in cmake, I got this error:

Administrator@WIN-GDGB8ICI8VS /c/mingw/msys/1.0/local/libArcus-2.4/build
$ cmake ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: C:/MinGW/msys/1.0/local/protobuf-3.0.0/src/.libs/libprotobuf.a (found suitable version "3.0.0", minimum required is "3.0.0")
-- Found PythonInterp: C:/python35/python.exe (found suitable version "3.5.3", minimum required is "3.4.0")
-- Found PythonLibs: C:/python35/libs/python35.lib (found suitable version "3.5.3", minimum required is "3.4.0")
CMake Error at cmake/FindSIP.cmake:64 (MESSAGE):
  Could not find SIP
Call Stack (most recent call first):
  CMakeLists.txt:22 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/MinGW/msys/1.0/local/libArcus-2.4/build/CMakeFiles/CMakeOutput.log".

Administrator@WIN-GDGB8ICI8VS /c/mingw/msys/1.0/local/libArcus-2.4/build
$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in yo
ur pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
setuptools (28.8.0)
sip (4.19.2)

When I try to set PYTHON_SITE_PACKAGES_DIR the error still exists.

**Comment by Ghostkeeper** [comment]
Do you have SIP installed? You can get it here: https://www.riverbankcomputing.com/software/sip/download

**Comment by masklu** [comment]
@Ghostkeeper ,when I installing SIP I get this error
$ make install
make[1]: Entering directory `/c/mingw/msys/1.0/local/sip-4.19.2/sipgen'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make[1]: *** [install] Error 2
make[1]: Leaving directory `/c/mingw/msys/1.0/local/sip-4.19.2/sipgen'
make: *** [install] Error 2

**Comment by masklu** [comment]
Hi,I solve the problem and have another question
Administrator@WIN-GDGB8ICI8VS /c/mingw/msys/1.0/local/libArcus-2.4/build
$ cmake ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: C:/MinGW/msys/1.0/local/protobuf-3.0.0/src/.libs/libprotobuf.a (found suitable version "3.0.0", minimum required is "3.0.0")
-- Found PythonInterp: C:/python35/python.exe (found suitable version "3.5.3", minimum required is "3.4.0")
-- Found PythonLibs: C:/python35/libs/python35.lib (found suitable version "3.5.3", minimum required is "3.4.0")
-- Found SIP version: 4.19.2
-- Configuring done
-- Generating done
-- Build files have been written to: C:/MinGW/msys/1.0/local/libArcus-2.4/build

Administrator@WIN-GDGB8ICI8VS /c/mingw/msys/1.0/local/libArcus-2.4/build
$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by masklu** [comment]
thanks,all problem solved

**Comment by Ghostkeeper** [comment]
If you can share what you did to solve it, perhaps that helps someone in the future!

**Comment by ewurman-dm** [comment]
@masklu 
I am getting the same error of
 $ make install
make[1]: Entering directory /c/mingw/msys/1.0/local/sip-4.19.2/sipgen' /bin/sh: -c: line 1: syntax error: unexpected end of file make[1]: *** [install] Error 2 make[1]: Leaving directory/c/mingw/msys/1.0/local/sip-4.19.2/sipgen'
make: *** [install] Error 2

do you remember how you fixed this?

**Comment by masklu** [comment]
@ewurman-dm 
like this Makefile
install:
	#@$(MAKE) -C sipgen install
	#@$(MAKE) -C siplib install
	#@if not exist c:\python35\Lib\site-packages mkdir c:\python35\Lib\site-packages
	#copy /y sipconfig.py c:\python35\Lib\site-packages\sipconfig.py
	#copy /y c:\mingw\msys\1.0\local\sip-4.19.2\sipdistutils.py c:\python35\Lib\site-packages\sipdistutils.py
 I just copy the file  follow install command  ,like copy sipdistutils.py to c:\python35\Lib\site-packages\
also in sipgen and siplib have Makefile and need to do the install command by yourself
I don't think it's a good way ,but it work,and I hope my broken English can tell clearly

**Comment by woshisuchao** [comment]
i have the same problem that "could not find sip" on widow cmake such like 
![image](https://user-images.githubusercontent.com/31384654/35133790-42d7284c-fd0d-11e7-8b60-6ebb20f44749.png)
and is that in window of your problem? why is there "$"

**Comment by masklu** [comment]
@woshisuchao install sip with Source Packages

**Comment by Ghostkeeper** [comment]
Please see https://github.com/Ultimaker/libArcus/issues/68. Don't post your issue it on every single ticket around.
