### ISSUE TITLE
Make Error of Libarcus while building CXX Object

### ISSUE THREAD

**Issue by Herry-Xu** [Ultimaker/libArcus#57]
I'm trying to build curaengine on a shared web hosting server where I **DO NOT** have root access and cannot use the package manager. I currently cannot get my Libarcus `make` to work. Any help or tips would be greatly appreciated.

**Notes:** I have been able to get cmake working with SIP by installing in a customized directory path; I've tried disabling python bindings by passing -DBUILD_PYTHON=OFF to CMakes.

#make
Scanning dependencies of target Arcus
[  4%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.o
In file included from /home2/thrdstre/bin/include/google/protobuf/message_lite.h:45,
                 from /home2/thrdstre/bin/include/google/protobuf/message.h:119,
                 from /home2/thrdstre/curaengine/libArcus/src/Socket_p.h:40,
                 from /home2/thrdstre/curaengine/libArcus/src/Socket.cpp:20:
/home2/thrdstre/bin/include/google/protobuf/generated_message_util.h:142: error: ISO C++ forbids declaration of 'constexpr' with no type
/home2/thrdstre/bin/include/google/protobuf/generated_message_util.h:144: error: expected ';' before 'const'
/home2/thrdstre/bin/include/google/protobuf/generated_message_util.h:148: error: expected ';' before 'T'
/home2/thrdstre/bin/include/google/protobuf/generated_message_util.h: In function 'const std::string& google::protobuf::internal::GetEmptyStringAlreadyInited()':
/home2/thrdstre/bin/include/google/protobuf/generated_message_util.h:173: error: 'class google::protobuf::internal::ExplicitlyConstructed<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >' has no member named 'get'
In file included from /home2/thrdstre/curaengine/libArcus/src/Socket_p.h:46,
                 from /home2/thrdstre/curaengine/libArcus/src/Socket.cpp:20:
/home2/thrdstre/curaengine/libArcus/src/SocketListener.h: In constructor 'Arcus::SocketListener::SocketListener()':
/home2/thrdstre/curaengine/libArcus/src/SocketListener.h:47: error: 'nullptr' was not declared in this scope
In file included from /home2/thrdstre/curaengine/libArcus/src/Socket_p.h:50,
                 from /home2/thrdstre/curaengine/libArcus/src/Socket.cpp:20:
/home2/thrdstre/curaengine/libArcus/src/WireMessage_p.h: In constructor 'Arcus::Private::WireMessage::WireMessage()':
/home2/thrdstre/curaengine/libArcus/src/WireMessage_p.h:52: error: 'nullptr' was not declared in this scope
In file included from /home2/thrdstre/curaengine/libArcus/src/Socket.cpp:20:
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h: In constructor 'Arcus::Socket::Private::Private()':
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:82: error: 'nullptr' was not declared in this scope
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h: In member function 'void Arcus::Socket::Private::error(Arcus::ErrorCode::ErrorCode, const std::string&)':
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:154: error: expected initializer before ':' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:158: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:158: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:158: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:158: error: expected ')' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:158: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:158: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h: In member function 'void Arcus::Socket::Private::fatalError(Arcus::ErrorCode::ErrorCode, const std::string&)':
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:172: error: expected initializer before ':' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:176: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:176: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:176: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:176: error: expected ')' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:176: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:176: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h: In member function 'void Arcus::Socket::Private::run()':
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:259: error: expected initializer before ':' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:264: error: could not convert 'Arcus::Socket::Private::receiveNextMessage()' to 'bool'
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:266: error: expected primary-expression before 'if'
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:266: error: expected ')' before 'if'
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:288: error: expected initializer before ':' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:296: error: expected ')' before ';' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:341: error: expected initializer before ':' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:345: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:345: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:345: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:345: error: expected ')' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:345: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:345: error: expected ';' before '}' token
In file included from /home2/thrdstre/curaengine/libArcus/src/Socket.cpp:20:
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h: In member function 'void Arcus::Socket::Private::handleMessage(const std::shared_ptr<Arcus::Private::WireMessage>&)':
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:558: error: expected initializer before ':' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:562: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:562: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:562: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:562: error: expected ')' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:562: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket_p.h:562: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp: In destructor 'virtual Arcus::Socket::~Socket()':
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:41: error: expected initializer before ':' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:45: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:45: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:45: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:45: error: expected ')' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:45: error: expected primary-expression before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:45: error: expected ';' before '}' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp: In member function 'void Arcus::Socket::connect(const std::string&, int)':
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:122: error: 'nullptr' was not declared in this scope
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:130: error: expected primary-expression before '[' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:130: error: expected primary-expression before ']' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp: In member function 'void Arcus::Socket::reset()':
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:145: error: 'nullptr' was not declared in this scope
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp: In member function 'void Arcus::Socket::listen(const std::string&, int)':
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:155: error: 'nullptr' was not declared in this scope
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:163: error: expected primary-expression before '[' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:163: error: expected primary-expression before ']' token
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp: In member function 'void Arcus::Socket::close()':
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:189: error: 'sleep_for' is not a member of 'std::this_thread'
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:206: error: 'nullptr' was not declared in this scope
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp: In member function 'Arcus::MessagePtr Arcus::Socket::takeNextMessage()':
/home2/thrdstre/curaengine/libArcus/src/Socket.cpp:233: error: 'nullptr' was not declared in this scope
make[2]: *** [CMakeFiles/Arcus.dir/src/Socket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Arcus.dir/all] Error 2
make: *** [all] Error 2

**Comment by LipuFei** [comment]
You have got this error a lot:
```
error: 'nullptr' was not declared in this scope
```
Could you check which GCC version you are using. You need at least GCC 4.6.0 to make it work. Here is a Stackoverflow link which explains this: https://stackoverflow.com/questions/3756473/what-header-file-needs-to-be-included-for-using-nullptr-in-g

**Comment by Herry-Xu** [comment]
Thanks for the quick reply! I can't update my GCC version since I don't have root access.  For the following nullptr workaround, do I need to access the GCC source files? Because once again, I would not have access to it.

const // this is a const object...
class {
public:
 template<class T> // convertible to any type
 operator T*() const // of null non-member
 { return 0; } // pointer...
 template<class C, class T> // or any type of null
 operator T C::*() const // member pointer...
 { return 0; }
private:
 void operator&() const; // whose address can't be taken
} nullptr = {}; // and whose name is nullptr

**Comment by LipuFei** [comment]
If you have to compile it on that server, I am afraid that you will need to compile your own GCC and many related libraries by yourself.

**Comment by Herry-Xu** [comment]
Okay thank you!

**Comment by Ghostkeeper** [comment]
> You need at least GCC 4.6.0 to make it work.

Correction: We require 4.9.2 or newer.
