### ISSUE TITLE
example.pb.h：No such file or directory

### ISSUE THREAD

**Issue by Eric-Hsia** [Ultimaker/libArcus#60]
Hi, is there anyone knows this issue,

when I make the libarcus on cygwin, it display below:

Scanning dependencies of target Arcus
[  4%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.o
[  9%] Building CXX object CMakeFiles/Arcus.dir/src/MessageTypeStore.cpp.o
[ 13%] Linking CXX shared library cygArcus-3.dll
[ 27%] Built target Arcus
Scanning dependencies of target python_module_Arcus
[ 31%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o
[ 36%] Linking CXX shared module Arcus.dll
[ 77%] Built target python_module_Arcus
[ 81%] Running C++ protocol buffer compiler on example.proto
[ 86%] Running Python protocol buffer compiler on example.proto
[ 90%] Building CXX object examples/CMakeFiles/example.dir/example.cpp.o
/cygdrive/d/slicer_base_CuraEngine/libArcus-master/examples/example.cpp:9:24: 致命错误(fatal error)：example.pb.h：No such file or directory
编译中断(compile stop)。
make[2]: *** [examples/CMakeFiles/example.dir/build.make:75：examples/CMakeFiles/example.dir/example.cpp.o] 错误 1(error 1)
make[1]: *** [CMakeFiles/Makefile2:160：examples/CMakeFiles/example.dir/all] 错误 2(error 2)
make: *** [Makefile:150：all] 错误 2(error 2)

**Comment by Ghostkeeper** [comment]
I'd expect `example.pb.h` to be created by Protobuf.

What happens when you manually call `protoc --python_out /cygdrive/d/slicer_base_CuraEngine/libArcus-master/examples --proto_path=/cygdrive/d/slicer_base_CuraEngine/libArcus-master/examples /cygdrive/d/slicer_base_CuraEngine/libArcus-master/examples/example.proto`? (You might have to replace `protoc` with a path to your protoc executable.)

Perhaps you have a buggy version of Protobuf?

**Comment by awhiemstra** [comment]
Note that you should use --cpp_out (or whatever it was that generates cpp files) since this is C++ code.

**Comment by Eric-Hsia** [comment]
Yes, you're right, I use the latest version, so that's the problem, thanks




发自网易邮箱大师
On 07/10/2017 07:08, Ghostkeeper wrote:

I'd expect example.pb.h to be created by Protobuf.

What happens when you manually call protoc --python_out /cygdrive/d/slicer_base_CuraEngine/libArcus-master/examples --proto_path=/cygdrive/d/slicer_base_CuraEngine/libArcus-master/examples /cygdrive/d/slicer_base_CuraEngine/libArcus-master/examples/example.proto? (You might have to replace protoc with a path to your protoc executable.)

Perhaps you have a buggy version of Protobuf?
