### ISSUE TITLE
Linux 64 bits issue

### ISSUE THREAD

**Issue by mariolpantunes** [Ultimaker/libArcus#61]
Hi, in order to compile Cura (and all the libs) I had to patch up the CMakeLists.txt to correctly use Lib_Suffix.
I share my lib64.patch, if you found it acceptable can you add it to the code?
[lib64.txt](https://github.com/Ultimaker/libArcus/files/1156522/lib64.txt)

**Comment by Ghostkeeper** [comment]
Thanks for the patch. I've made some slight alterations to it since sources on the internet say that the `LIB_SUFFIX` variable isn't always defined. It still works on my debian-based system since it was defined to the empty string, but I made a check to ensure it is defined anyway to be safe.
