### ISSUE TITLE
libArcus make error in Windows

### ISSUE THREAD

**Issue by yingzhang1109** [Ultimaker/libArcus#62]
I installed protobuf and run cmake ..    here is what I have 
D:\VS\VC>cd D:\Engine\libArcus-2.6\build

D:\Engine\libArcus-2.6\build>cmake ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: D:/VS/VC/bin/cl.exe
-- Check for working C compiler: D:/VS/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: D:/VS/VC/bin/cl.exe
-- Check for working CXX compiler: D:/VS/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at C:/Program Files (x86)/CMake/share/cmake-3.8/Modules/FindProtobuf.cmake:387 (message):
  Protobuf compiler version doesn't match library version 3.3.0
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)

-- Found Protobuf: D:/Engine/protobuf-3.3.0/install/x86/release/lib/libprotobufd.lib (found suitable version "3.3.0", minimum required is "3.0.0")
-- Found PythonInterp: D:/python 3.5/python.exe (found suitable version "3.5.3", minimum required is "3.4.0")
-- Found PythonLibs: D:/python 3.5/libs/python35.lib (found suitable version "3.5.3", minimum required is "3.4.0")
-- Found SIP version: 4.19.1
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Engine/libArcus-2.6/build

D:\Engine\libArcus-2.6\build>mingw32-make
mingw32-make: *** No targets specified and no makefile found.  Stop.

I am not sure why it's not working for mingw32-make? anyone can help?

**Comment by Ghostkeeper** [comment]
Your CMake is set to generate Visual Studio files by default, and then you're trying to make using MinGW. Try this instead of your `cmake ..`:

    cmake -G "MinGW Makefiles" ..

This generates Makefiles for MinGW so that you can call `mingw32-make` next.

You're also going to have to use nmake after this, if you want to compile Python bindings. This has a similar process.

**Comment by woshisuchao** [comment]
![image](https://user-images.githubusercontent.com/31384654/35133893-ce097b0e-fd0d-11e7-9aed-67bacdcc876a.png)
why i could find SIP

**Comment by Ghostkeeper** [comment]
This is a closed issue with a different problem. Please create a new ticket.

FindSIP starts the Python installation and calls `import sip` there. So it executes this:

    "C:\Users\one piece\AppData\Local\Programs\Python\Python35\python.exe" -c "import sip"

The difference in your case may be that you're calling `pip3` but it's using `python.exe`, not `python3.exe`. Instead, it's always better to call the correct Python executable directly to install via Pip, like so:

    "C:\Users\one piece\AppData\Local\Programs\Python\Python35\python.exe" -m pip install sip

**Comment by Ghostkeeper** [comment]
Please see the separate ticket you made about this: https://github.com/Ultimaker/libArcus/issues/68

It's a bad idea to post your problem in all of the other guys' issues.
