### ISSUE TITLE
protobuf problem when using cmake gui

### ISSUE THREAD

**Issue by yingzhang1109** [Ultimaker/libArcus#63]
I am trying to use cmake gui to generate the cmake files. here is my error. could anyone help me on that? thanks in advance
![image](https://user-images.githubusercontent.com/25900394/28558292-dda9fc42-7143-11e7-81bc-f9f08294e71e.png)

**Comment by nallath** [comment]
Don't build the tests.

**Comment by yingzhang1109** [comment]
@nallath thank you for your response! and how can I do it?

**Comment by awhiemstra** [comment]
One of the options in the CMake config is something along the lines of BUILD_TESTING or protobuf_BUILD_TESTS or so. Disable that one to disable building the tests.

**Comment by yingzhang1109** [comment]
@awhiemstra thank you for your response. I have another question. I sussesfully installed the protobuf with no error, but I met the problem in installing the LibArcus. It's said Could NOT find Protobuf.
![image](https://user-images.githubusercontent.com/25900394/28600977-16753e0c-71e8-11e7-8877-85490d6fe670.png)
do you have any idea about this?

**Comment by awhiemstra** [comment]
You can use cmake-gui to point Arcus' build system at the right location for protobuf. It should have the two mentioned variables (Protobuf_LIBRARIES and Protobuf_INCLUDE_DIR) that you can set.

**Comment by yingzhang1109** [comment]
@awhiemstra thanks for your reply. I use cmake-gui to figure out it, and I have another problem.
![image](https://user-images.githubusercontent.com/25900394/28805607-e7cfe182-769d-11e7-8aa7-89df5730bcbc.png)
that's what I have now, and I run the command window and run mingw32-make; nmake; make. none of them are working. 
![image](https://user-images.githubusercontent.com/25900394/28805681-62c80798-769e-11e7-89f3-fae7a4518f7d.png)
what should i do in this situation?

**Comment by yingzhang1109** [comment]
@awhiemstra thanks for your reply, and I have another problem that, when I run mingw32-make
that's what I have
![image](https://user-images.githubusercontent.com/25900394/28806700-fb72ccc6-76a3-11e7-950d-e226fc9d4f2c.png)
do you know how can I fix that problem?

**Comment by yingzhang1109** [comment]
I figured it out

**Comment by Ghostkeeper** [comment]
What was your solution? It looks like something with mixing up different compilers.

**Comment by yingzhang1109** [comment]
@Ghostkeeper yes, it's because of the compulers
