### ISSUE TITLE
libArcus make fail;  too many initializers/sipArcuspart0.cpp.o' failed

### ISSUE THREAD

**Issue by okayauco** [Ultimaker/libArcus#65]
Hi, I managed to solve the FindSIP issue by installing `python3-sip-dev,` so now it shows `Found SIP version: 4.18.1` even though running `sip -V`still shows 4.19.3.  Shrug.  But now I get this error when attempting to `sudo make`

Using Ubuntu  17.04

> 
> [ 31%] Generating python/sipArcuspart0.cpp, python/sipArcuspart1.cpp, python/sipArcuspart2.cpp, python/sipArcuspart3.cpp, python/sipArcuspart4.cpp, python/sipArcuspart5.cpp, python/sipArcuspart6.cpp, python/sipArcuspart7.cpp
> 
> Scanning dependencies of target python_module_Arcus
> [ 36%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart0.cpp.o
> In file included from /home/stine/libArcus/build/python/sipArcuspart0.cpp:10:0:
> /home/stine/libArcus/build/python/sipArcuspart0.cpp: In function ‘void sipVH_Arcus_2(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper*, PyObject*, const Arcus::Error&)’:
> /home/stine/libArcus/build/python/sipAPIArcus.h:153:51: error: ‘const sipAPIDef {aka const struct _sipAPIDef}’ has no member named ‘api_call_procedure_method’; did you mean ‘api_call_method’?
>  #define sipCallProcedureMethod      sipAPI_Arcus->api_call_procedure_method
>                                                    ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:83:5: note: in expansion of macro ‘sipCallProcedureMethod’
>      sipCallProcedureMethod(sipGILState, sipErrorHandler, sipPySelf, sipMethod, "N", new  ::Error(a0), sipType_Error, NULL);
>      ^~~~~~~~~~~~~~~~~~~~~~
> /home/stine/libArcus/build/python/sipArcuspart0.cpp: In function ‘void sipVH_Arcus_1(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper*, PyObject*)’:
> /home/stine/libArcus/build/python/sipAPIArcus.h:153:51: error: ‘const sipAPIDef {aka const struct _sipAPIDef}’ has no member named ‘api_call_procedure_method’; did you mean ‘api_call_method’?
>  #define sipCallProcedureMethod      sipAPI_Arcus->api_call_procedure_method
>                                                    ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:88:5: note: in expansion of macro ‘sipCallProcedureMethod’
>      sipCallProcedureMethod(sipGILState, sipErrorHandler, sipPySelf, sipMethod, "");
>      ^~~~~~~~~~~~~~~~~~~~~~
> /home/stine/libArcus/build/python/sipArcuspart0.cpp: In function ‘void sipVH_Arcus_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper*, PyObject*, Arcus::SocketState::SocketState)’:
> /home/stine/libArcus/build/python/sipAPIArcus.h:153:51: error: ‘const sipAPIDef {aka const struct _sipAPIDef}’ has no member named ‘api_call_procedure_method’; did you mean ‘api_call_method’?
>  #define sipCallProcedureMethod      sipAPI_Arcus->api_call_procedure_method
>                                                    ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:93:5: note: in expansion of macro ‘sipCallProcedureMethod’
>      sipCallProcedureMethod(sipGILState, sipErrorHandler, sipPySelf, sipMethod, "F", a0, sipType_SocketState_SocketState);
>      ^~~~~~~~~~~~~~~~~~~~~~
> /home/stine/libArcus/build/python/sipArcuspart0.cpp: At global scope:
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:98:1: error: too many initializers for ‘sipTypeDef {aka _sipTypeDef}’
>  };
>  ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:98:1: error: too many initializers for ‘sipTypeDef {aka _sipTypeDef}’
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:145:1: error: braces around scalar initializer for type ‘void (**)(_sipSimpleWrapper*, sip_gilstate_t) {aka void (**)(_sipSimpleWrapper*, PyGILState_STATE)}’
>  };
>  ^
> In file included from /home/stine/libArcus/build/python/sipArcuspart0.cpp:10:0:
> /home/stine/libArcus/build/python/sipArcuspart0.cpp: In destructor ‘virtual sipSocket::~sipSocket()’:
> /home/stine/libArcus/build/python/sipAPIArcus.h:160:51: error: ‘const sipAPIDef {aka const struct _sipAPIDef}’ has no member named ‘api_instance_destroyed’; did you mean ‘api_abstract_method’?
>  #define sipInstanceDestroyed        sipAPI_Arcus->api_instance_destroyed
>                                                    ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:301:5: note: in expansion of macro ‘sipInstanceDestroyed’
>      sipInstanceDestroyed(sipPySelf);
>      ^~~~~~~~~~~~~~~~~~~~
> /home/stine/libArcus/build/python/sipArcuspart0.cpp: In function ‘void dealloc_Socket(sipSimpleWrapper*)’:
> /home/stine/libArcus/build/python/sipAPIArcus.h:272:51: error: ‘const sipAPIDef {aka const struct _sipAPIDef}’ has no member named ‘api_is_derived_class’; did you mean ‘api_find_class’?
>  #define sipIsDerivedClass           sipAPI_Arcus->api_is_derived_class
>                                                    ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:691:9: note: in expansion of macro ‘sipIsDerivedClass’
>      if (sipIsDerivedClass(sipSelf))
>          ^~~~~~~~~~~~~~~~~
> /home/stine/libArcus/build/python/sipAPIArcus.h:271:51: error: ‘const sipAPIDef {aka const struct _sipAPIDef}’ has no member named ‘api_is_owned_by_python’; did you mean ‘api_is_py_method’?
>  #define sipIsOwnedByPython          sipAPI_Arcus->api_is_owned_by_python
>                                                    ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:694:9: note: in expansion of macro ‘sipIsOwnedByPython’
>      if (sipIsOwnedByPython(sipSelf))
>          ^~~~~~~~~~~~~~~~~~
> /home/stine/libArcus/build/python/sipAPIArcus.h:272:51: error: ‘const sipAPIDef {aka const struct _sipAPIDef}’ has no member named ‘api_is_derived_class’; did you mean ‘api_find_class’?
>  #define sipIsDerivedClass           sipAPI_Arcus->api_is_derived_class
>                                                    ^
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:696:48: note: in expansion of macro ‘sipIsDerivedClass’
>          release_Socket(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
>                                                 ^~~~~~~~~~~~~~~~~
> /home/stine/libArcus/build/python/sipArcuspart0.cpp: At global scope:
> /home/stine/libArcus/build/python/sipArcuspart0.cpp:787:1: error: too many initializers for ‘sipTypeDef {aka _sipTypeDef}’
>  };
>  ^
> CMakeFiles/python_module_Arcus.dir/build.make:93: recipe for target 'CMakeFiles/python_module_Arcus.dir/python/sipArcuspart0.cpp.o' failed
> make[2]: *** [CMakeFiles/python_module_Arcus.dir/python/sipArcuspart0.cpp.o] Error 1
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/python_module_Arcus.dir/all' failed
> make[1]: *** [CMakeFiles/python_module_Arcus.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by nallath** [comment]
Did you try make clean first?

**Comment by okayauco** [comment]
Umm..I did not, but what I did was run the cura-build-environment stuff and it installed SIP correctly and afterwards when I did make install, it worked then.  Shrug.  Thank you!
