### ISSUE TITLE
Arcus with VC

### ISSUE THREAD

**Issue by woshisuchao** [Ultimaker/libArcus#68]
![image](https://user-images.githubusercontent.com/31384654/35132054-4c3e7628-fd04-11e7-9731-16b5b6892224.png)

![image](https://user-images.githubusercontent.com/31384654/35132020-25379712-fd04-11e7-9802-a41ca667025b.png)
![image](https://user-images.githubusercontent.com/31384654/35132026-2c142974-fd04-11e7-9b93-f62c6ee0e0d6.png)

give me instrution,thankyou...

**Comment by Ghostkeeper** [comment]
FindSIP starts the Python installation and calls `import sip` there. So it executes this:

    "C:\Users\one piece\AppData\Local\Programs\Python\Python35\python.exe" -c "import sip"

The difference in your case may be that you're calling `pip3` but it's using `python.exe`, not `python3.exe`. Instead, it's always better to call the correct Python executable directly to install via Pip, like so:

    "C:\Users\one piece\AppData\Local\Programs\Python\Python35\python.exe" -m pip install sip

**Comment by woshisuchao** [comment]
yeh thank you , i have resolved this problem , i am a beginer, so many thing i dont know, so turn to internet for help, thank you
