### ISSUE TITLE
Remove the Debian hack from CMakeLists.txt

### ISSUE THREAD

**Issue by onitake** [Ultimaker/libArcus#81]
This issue applies to all Cura repositories. I'd like to discuss it here first, because it's most important for the SIP modules.

The Debian project has recently started to migrate to Python 3.7. In the course of this, it was discovered that the build scripts for libArcus, libSavitar et al were not capable of producing modules for all installed Python versions on the system. During the upgrade phase, both Python 3.6 and 3.7 will be available and all Python packages should build against both.
Part of the reason is the "Debian hack" in [CMakeLists.txt#L29-L32](https://github.com/Ultimaker/libArcus/blob/master/CMakeLists.txt#L29-L32).

However, we also discovered something else that will solve both problems at once:
If the Debian packages are built with pybuild instead of cmake directly, pybuild will take care of renaming and moving the modules to the "correct" location in Debian systems. Plus, it will run the build process once for each installed Python version - producing modules for _all_ of them!

This is our fix: https://salsa.debian.org/3dprinting-team/libarcus/commit/5a9f763e18c4ada320f99d06bf32d6b770473220

And here's just the CMakeLists.txt patch: https://salsa.debian.org/3dprinting-team/libarcus/blob/master/debian/patches/02-add-python-version.patch

I can submit a PR for libArcus and all other Cura repositories if this is useful to you. We will keep the patch in the Debian build repos otherwise.

**Comment by onitake** [comment]
I should also note that the packages in Ubuntu are based on the Debian ones and while I can't test cross-building right now, I'm quite certain they will build and work fine with this change. I'll discuss it with the Ubuntu maintainer.

**Comment by rburema** [comment]
Hi @onitake,
Sorry it took so long to get back. We've decided that we'd like to have the PR. It might take us a while to get to it (we've got a bit of a backlog), but at least it will be in the pipeline then.
kind regards, Remco.

**Comment by onitake** [comment]
All right!
As soon as I've updated all Debian packages with the patch and tested them, I'll submit a PR for each Repo.

**Comment by thopiekar** [comment]
Btw. removing the hack is included here: https://github.com/Ultimaker/libArcus/pull/90
Haven't seen @onitake 's changes, but that's the most recent way to determine the site-packages path.
CMake introduced since 3.12 release.

I think since we need the most recent software like Qt, then we can also depend on more recent build tools, too. However, only my opinion of course.

**Comment by Ghostkeeper** [comment]
Should be fixed with https://github.com/Ultimaker/libArcus/pull/94 .
