### ISSUE TITLE
undefined reference to google::protobuf

### ISSUE THREAD

**Issue by Making-It** [Ultimaker/libArcus#95]
Hello, I am building Cura's build environment, but when I compile libArcus on Windows 7 virtual machine, I reported the program link error. Please see the picture for the error message. On this basis, I have installed protobuf and also add it to environment variable.

![1554198404772](C:\Users\xcg\AppData\Roaming\Typora\typora-user-images\1554198404772.png)

This problem has been bothering me for a few days. If there is time, please give me some solutions. Thank you!!!

**Comment by Ghostkeeper** [comment]
I think your picture broke.
