### ISSUE TITLE
Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)

### ISSUE THREAD

**Issue by CatchZeng** [Ultimaker/libArcus#97]
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
  (Required is at least version "3.0.0")
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindProtobuf.cmake:594 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:19 (find_package)

**Comment by Ghostkeeper** [comment]
Try setting `Protobuf_LIBRARIES` to where your Protobuf libraries are and `Protobuf_INCLUDE_DIR` to where your Protobuf headers are.
